import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800', '900'],
  preload: false,
});

export const metadata = {
  title: 'Brigher Days ',
  description: 'Generated by Brigher Days',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/svg+xml" href="/logo.png" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
